name: AC-Essentials
version: "1.0"
author: socialclubz.com
api: ["1.0.0"]
main: me.socialclubz.com.essentials
commands:
  heal:
    description: Recover your hearts
    permission: social.heal
  eat:
    description: Recover your hunger
    permission: social.eat
  healer:
    description: Completly heals all
    permission: social.healer
  ext:
    description: Takes the fire away
    permission: social.ext
  scc:
    description: Clear global chat
    permission: social.scc
  cc:
    description: Clear personal chat
    permission: social.cc
  fly:
    description: Let you fly around the world
    permission: social.fly
  ci:
    description: Clears your inventory
    permission: social.ci